 const navigation = [
   {
     title: 'CSS Tools',
     live: true,
     links: [
       { title: 'REM to Pixel Converter', href: '/rem-to-pixel-converter' },
       { title: 'REM to Percent Converter', href: '/rem-to-percent-converter' },
       { title: 'REM to Point Converter', href: '/rem-to-point-converter' },
       { title: 'EM to Pixel Converter', href: '/em-to-pixel-converter' },
       { title: 'EM to Percent Converter', href: '/em-to-percent-converter' },
       { title: 'EM to Point Converter', href: '/em-to-point-converter' },

       { title: 'Pixel to EM Converter', href: '/pixel-to-em-converter' },
       { title: 'Pixel to REM Converter', href: '/pixel-to-rem-converter' },
       {
         title: 'Pixel to Percent Converter',
         href: '/pixel-to-percent-converter',
       },
       { title: 'Pixel to Point Converter', href: '/pixel-to-point-converter' },

       { title: 'Point to EM Converter', href: '/point-to-em-converter' },
       { title: 'Point to REM Converter', href: '/point-to-rem-converter' },
       {
         title: 'Point to Percent Converter',
         href: '/point-to-percent-converter',
       },
       { title: 'Point to Pixel Converter', href: '/point-to-pixel-converter' },

       { title: 'Percent to EM Converter', href: '/percent-to-em-converter' },
       { title: 'Percent to REM Converter', href: '/percent-to-rem-converter' },
       {
         title: 'Percent to Point Converter',
         href: '/percent-to-point-converter',
       },
       {
         title: 'Percent to Pixel Converter',
         href: '/percent-to-pixel-converter',
       },

       //  { title: 'CSS Beautifier', href: '#' },
       //  { title: 'CSS to LESS', href: '#' },
       //  { title: 'CSS to SCSS', href: '#' },
       //  { title: 'CSS to SASS', href: '#' },
       //  { title: 'CSS to Stylus', href: '#' },
       //  { title: 'Stylus Compiler', href: '#' },
       //  { title: 'Stylus to CSS', href: '#' },
       //  { title: 'Stylus to LESS', href: '#' },
       //  { title: 'Stylus to SCSS', href: '#' },
       //  { title: 'Stylus to SASS', href: '#' },
       //  { title: 'LESS Compiler', href: '#' },
       //  { title: 'LESS to CSS', href: '#' },
       //  { title: 'LESS to Stylus', href: '#' },
       //  { title: 'LESS to SCSS', href: '#' },
       //  { title: 'LESS to SASS', href: '#' },
       //  { title: 'SCSS Compiler', href: '#' },
       //  { title: 'SCSS to CSS', href: '#' },
       //  { title: 'SCSS to Stylus', href: '#' },
       //  { title: 'SCSS to LESS', href: '#' },
       //  { title: 'SCSS to SASS', href: '#' },
       //  { title: 'SASS Compiler', href: '#' },
       //  { title: 'SASS to CSS', href: '#' },
       //  { title: 'SASS to Stylus', href: '#' },
       //  { title: 'SASS to SCSS', href: '#' },
       //  { title: 'SASS to LESS', href: '#' },
       //  { title: 'Escape Unescape', href: '#' },
     ],
   },
   {
     title: 'Beautifiers',
     live: false,
     links: [
       { title: 'CSS Beautifier', href: '#' },
       { title: 'XML Beautifier', href: '#' },
       { title: 'HTML Beautifier', href: '#' },
       { title: 'JSON Beautifier', href: '#' },
       { title: 'Javascript Beautifier', href: '#' },
       { title: 'YAML Beautifier', href: '#' },
       { title: 'C# Beautifier', href: '#' },
       { title: 'Java Beautifier', href: '#' },
       { title: 'C Beautifier', href: '#' },
       { title: 'C++ Beautifier', href: '#' },
       { title: 'TypeScript Formatter', href: '#' },
       { title: 'SQL Formatter', href: '#' },
       { title: 'Babel Formatter', href: '#' },
       { title: 'Markdown Formatter', href: '#' },
       { title: 'MDX Formatter', href: '#' },
       { title: 'LESS Beautifier', href: '#' },
       { title: 'SCSS Beautifier', href: '#' },
       { title: 'GraphQL Beautifier', href: '#' },
       { title: 'PHP Beautifier', href: '#' },
       { title: 'Python Beautifier', href: '#' },
       { title: 'Perl Beautifier', href: '#' },
       { title: 'Ruby Beautifier', href: '#' },
       { title: 'Angular Formatter', href: '#' },
       { title: 'React Formatter', href: '#' },
       { title: 'Lua Beautifier', href: '#' },
       { title: 'XAML Beautifier', href: '#' },
     ],
   },
   {
     title: 'Minify',
     live: false,
     links: [
       { title: 'XML Minify', href: '#' },
       { title: 'Minify JS', href: '#' },
       { title: 'CSS Minify', href: '#' },
       { title: 'SQL Minifier', href: '#' },
       { title: 'Minify HTML', href: '#' },
       { title: 'Lua Minifier', href: '#' },
       { title: 'Text Minifier', href: '#' },
     ],
   },
   {
     title: 'CSV Tools',
     live: false,
     links: [
       { title: 'CSV Viewer', href: '#' },
       { title: 'CSV to XML/JSON', href: '#' },
       { title: 'CSV to XML', href: '#' },
       { title: 'CSV to JSON', href: '#' },
       { title: 'CSV to HTML', href: '#' },
       { title: 'CSV to TSV', href: '#' },
       { title: 'CSV to MULTILINE DATA', href: '#' },
       { title: 'CSV to SQL', href: '#' },
       { title: 'CSV to Excel', href: '#' },
     ],
   },
   {
     title: 'String Utilities',
     live: false,
     links: [
       { title: 'Upside Down Text', href: '#' },
       { title: 'Random Word Generator', href: '#' },
       { title: 'NTLM Hash Generator', href: '#' },
       { title: 'Password Generator', href: '#' },
       { title: 'String Builder', href: '#' },
       { title: 'Number to Word Converter', href: '#' },
       { title: 'Word to Number Converter', href: '#' },
       { title: 'WORD COUNTER', href: '#' },
       { title: 'Word Repeater', href: '#' },
       { title: 'Reverse String', href: '#' },
       { title: 'String to Hex Converter', href: '#' },
       { title: 'Hex to String Converter', href: '#' },
       { title: 'String to Binary Converter', href: '#' },
       { title: 'Binary to String Converter', href: '#' },
       { title: 'Case Converter', href: '#' },
       { title: 'Delimited Text Extractor', href: '#' },
       { title: 'Remove Accents', href: '#' },
       { title: 'Remove Duplicate Lines', href: '#' },
       { title: 'Remove Empty Lines', href: '#' },
       { title: 'Remove Extra Spaces', href: '#' },
       { title: 'Remove Whitespace', href: '#' },
       { title: 'Remove Line Breaks', href: '#' },
       { title: 'Remove Lines Containing', href: '#' },
       { title: 'Sort Text Lines', href: '#' },
       { title: 'Word Sorter', href: '#' },
       { title: 'Word Frequency Counter', href: '#' },
       { title: 'Text Repeater', href: '#' },
       { title: 'Remove Punctuation', href: '#' },
     ],
   },
   {
     title: 'Cryptography Tools',
     live: false,
     links: [
       { title: 'Encryption-Decryption', href: '#' },
       { title: 'HMAC Generator', href: '/hmac-generator' },
       { title: 'MD2 Hash Generator', href: '#' },
       { title: 'MD4 Hash Generator', href: '#' },
       { title: 'MD5 Hash Generator', href: '#' },
       { title: 'MD6 Hash Generator', href: '#' },
       { title: 'NTLM Hash Generator', href: '#' },
       { title: 'SHA1 Hash Generator', href: '#' },
       { title: 'SHA2 Hash Generator', href: '#' },
       { title: 'SHA224 Hash Generator', href: '#' },
       { title: 'SHA256 Hash Generator', href: '#' },
       { title: 'SHA384 Hash Generator', href: '#' },
       { title: 'SHA512 Hash Generator', href: '#' },
       { title: 'SHA512/224 Hash Generator', href: '#' },
       { title: 'SHA512/256 Hash Generator', href: '#' },
       { title: 'SHA3-224 Hash Generator', href: '#' },
       { title: 'SHA3-256 Hash Generator', href: '#' },
       { title: 'SHA3-384 Hash Generator', href: '#' },
       { title: 'SHA3-512 Hash Generator', href: '#' },
       { title: 'CRC-16 Hash Generator', href: '#' },
       { title: 'CRC-32 Hash Generator', href: '#' },
       { title: 'Shake-128 Hash Generator', href: '#' },
       { title: 'Shake-256 Hash Generator', href: '#' },
       { title: 'Whirlpool Hash Generator', href: '#' },
       { title: 'Wordpress Password Hash Generator', href: '#' },
     ],
   },
   {
     title: 'Escape Unescape',
     live: false,
     links: [
       { title: 'HTML Escape Unescape', href: '#' },
       { title: 'XML Escape Unescape', href: '#' },
       { title: 'Java Escape Unescape', href: '#' },
       { title: 'C# Escape Unescape', href: '#' },
       { title: 'Javascript Escape Unescape', href: '#' },
       { title: 'CSV Escape Unescape', href: '#' },
       { title: 'SQL Escape Unescape', href: '#' },
       { title: 'JSON Escape Unescape', href: '#' },
       { title: 'Un-Google Link', href: '#' },
       { title: 'CryptoGraphy Tools', href: '#' },
     ],
   },
   {
     title: 'Parsers',
     live: false,
     links: [
       { title: 'URL Parser', href: '#' },
       { title: 'JSON Parser', href: '#' },
       { title: 'XML Parser', href: '#' },
       { title: 'YAML Parser', href: '#' },
     ],
   },
   {
     title: 'Programming Editors',
     live: false,
     links: [
       { title: 'XML Editor', href: '#' },
       { title: 'JSON Editor', href: '#' },
       { title: 'Real Time HTML Editor', href: '#' },
       { title: 'YAML Editor', href: '#' },
       { title: 'ONLINE Editor', href: '#' },
       { title: 'JAVA Editor', href: '#' },
       { title: 'C# Editor', href: '#' },
       { title: 'Actionscript Editor', href: '#' },
       { title: 'Markdown Editor', href: '#' },
     ],
   },
   {
     title: 'Viewers',
     live: false,
     links: [
       { title: 'JSON Viewer', href: '#', key: 'viewer1' },
       { title: 'XML Viewer', href: '#', key: 'viewer2' },
       { title: 'YAML Viewer', href: '#', key: 'viewer3' },
       { title: 'MXML Viewer', href: '#', key: 'viewer4' },
       { title: 'HTML Viewer', href: 'html-viewer', key: 'viewer5' },
       { title: 'JavaScript Viewer', href: '#', key: 'viewer6' },
       { title: 'RSS Viewer', href: '#', key: 'viewer7' },
       { title: 'SOURCE CODE Viewer', href: '#', key: 'viewer8' },
       { title: 'OPML Viewer', href: '#', key: 'viewer9' },
       { title: 'CSV Viewer', href: '#', key: 'viewer10' },
       { title: 'BBCode Viewer', href: '#', key: 'viewer11' },
       { title: 'Markdown Viewer', href: '#', key: 'viewer12' },
     ],
   },
   {
     title: 'Chart Tools',
     live: false,
     links: [
       { title: 'Line Graph Maker', href: '#' },
       { title: 'Bar Graph Maker', href: '#' },
       { title: 'Pie Chart Maker', href: '#' },
       { title: 'Doughnut Chart Maker', href: '#' },
       { title: 'Scatter Plot Maker', href: '#' },
     ],
   },
   {
     title: 'Utility',
     live: false,
     links: [
       { title: 'Send Snap Message', href: '#' },
       { title: 'Responsive Website Tester', href: '#' },
       { title: 'Credit Card Validator', href: '#' },
       { title: 'Credit Card Fake Number Generator', href: '#' },
       { title: 'XPath Tester', href: '#' },
       { title: 'JSON Path Tester', href: '#' },
       { title: 'JSON Minifier', href: '#' },
       { title: 'File Difference', href: '#' },
       { title: 'JSON Diff', href: '#' },
       { title: 'XML Diff', href: '#' },
       { title: 'Broken Link Checker', href: '#' },
       { title: 'JSON Deserialize Online', href: '#' },
       { title: 'JSON Serialize Online', href: '#' },
       { title: 'JSON Stringify Online', href: '#' },
       { title: 'XML Stringify Online', href: '#' },
       { title: 'String to JSON Online', href: '#' },
       { title: 'JavaScript Obfuscator', href: '#' },
       { title: 'Curl to PHP', href: '#' },
       { title: 'Crontab Format', href: '#' },
     ],
   },
   {
     title: 'YAML Converters',
     live: false,
     links: [
       { title: 'YAML Converter', href: '#' },
       { title: 'YAML to XML', href: '#' },
       { title: 'YAML to JSON', href: '#' },
       { title: 'YAML to CSV', href: '#' },
       { title: 'YAML to Excel', href: '#' },
     ],
   },
   {
     title: 'HTML Converters',
     live: false,
     links: [
       { title: 'HTML Stripper', href: '#' },
       { title: 'HTML Table Generator', href: '#' },
       { title: 'HTML to CSV Converter', href: '#' },
       { title: 'HTML to TSV Converter', href: '#' },
       { title: 'HTML to PHP Converter', href: '#' },
       { title: 'HTML to CSV', href: '#' },
       { title: 'HTML to JSON', href: '#' },
       { title: 'HTML to XML', href: '#' },
       { title: 'HTML to YAML', href: '#' },
       { title: 'HTML to Text', href: '#' },
       { title: 'Text to HTML Entities', href: '#' },
       { title: 'HTML Entities to Text', href: '#' },
       { title: 'HTML to Markdown', href: '#' },
       { title: 'Markdown to HTML', href: '#' },
       { title: 'PUG to HTML Converter', href: '#' },
       { title: 'HTML to PUG Converter', href: '#' },
       { title: 'JADE to HTML Converter', href: '#' },
       { title: 'HTML to JADE Converter', href: '#' },
       { title: 'HTML to BBCode Converter', href: '#' },
       { title: 'BBCode to HTML Converter', href: '#' },
     ],
   },
   {
     title: 'XML Converters',
     live: false,
     links: [
       { title: 'XML Converter', href: '#' },
       { title: 'XML to JSON', href: '#' },
       { title: 'XML to YAML', href: '#' },
       { title: 'XML to CSV', href: '#' },
       { title: 'XML to TSV', href: '#' },
       { title: 'XML to Text', href: '#' },
       { title: 'XML-XSL Transform', href: '#' },
       { title: 'XML to HTML', href: '#' },
       { title: 'XML to Excel', href: '#' },
       { title: 'XML to JAVA', href: '#' },
     ],
   },
   {
     title: 'JSON Converters',
     live: false,
     links: [
       { title: 'JSON to JAVA', href: '#' },
       { title: 'JSON to XML', href: '#' },
       { title: 'JSON to YAML', href: '#' },
       { title: 'JSON to CSV', href: '#' },
       { title: 'JSON to TSV', href: '#' },
       { title: 'JSON to Text', href: '#' },
       { title: 'JSON to Excel', href: '#' },
       { title: 'JSON to HTML', href: '#' },
     ],
   },
   {
     title: 'Converters',
     live: false,
     links: [
       { title: 'Image to Base64', href: '#' },
       { title: 'Base64 to Image', href: '#' },
       { title: 'Date Calculater', href: '#' },
       { title: 'EXCEL to HTML', href: '#' },
       { title: 'EXCEL to XML', href: '#' },
       { title: 'EXCEL to JSON', href: '#' },
       { title: 'OPML to JSON', href: '#' },
       { title: 'Word to HTML', href: '#' },
       { title: 'Online Tableizer', href: '#' },
     ],
   },
   {
     title: 'Image Tools',
     live: false,
     links: [
       { title: 'JPG to PNG', href: '#' },
       { title: 'BMP to PNG', href: '#' },
       { title: 'PNG to JPG', href: '#' },
       { title: 'GIF Splitter', href: '#' },
       { title: 'GIF Viewer', href: '#' },
       { title: 'More Image Tools', href: '#' },
     ],
   },
   {
     title: 'Base64 Tools',
     live: true,
     links: [
       { title: 'Image to Base64', href: '/image-to-base64' },
       { title: 'Base64 to Image', href: '/base64-to-image' },
       { title: 'JSON to Base64', href: '/json-to-base64' },
       { title: 'Base64 Encode', href: '/base64-encode' },
       { title: 'Base64 Decode', href: '/base64-decode' },
       { title: 'Base64 to ASCII', href: '/base64-to-ascii' },
       { title: 'Numbers to Words', href: '/number-to-words' },

       //  { title: 'XML to Base64', href: '#' },
       //  { title: 'YAML to Base64', href: '#' },
       //  { title: 'Base64 to JSON', href: '#' },
       //  { title: 'Base64 to XML', href: '#' },
       //  { title: 'Base64 to YAML', href: '#' },
       //  { title: 'CSV to Base64', href: '#' },
       //  { title: 'Base64 to CSV', href: '#' },
       //  { title: 'TSV to Base64', href: '#' },
       //  { title: 'Base64 to TSV', href: '#' },
       //  { title: 'Binary to Base64', href: '#' },
       //  { title: 'Base64 to Binary', href: '#' },
       //  { title: 'Hex to Base64', href: '#' },
       //  { title: 'Base64 to Hex', href: '#' },
       //  { title: 'Octal to Base64', href: '#' },
       //  { title: 'More Base64 Tools', href: '#' },
       //  { title: 'PNG to Base64', href: '#' },
       //  { title: 'JPG to Base64', href: '#' },
     ],
   },
   {
     title: 'Encode and Decode',
     live: false,
     links: [
       { title: 'Base32 Encode', href: '#' },
       { title: 'Base32 Decode', href: '#' },
       { title: 'Base58 Encode', href: '#' },
       { title: 'Base58 Decode', href: '#' },
       { title: 'Base64 Encode', href: '#' },
       { title: 'Base64 Decode', href: '#' },
       { title: 'URL Encode Online', href: '#' },
       { title: 'URL Decode Online', href: '#' },
       { title: 'JSON URL Encode', href: '#' },
       { title: 'JSON URL Decode', href: '#' },
       { title: 'HTML Encode', href: '#' },
       { title: 'HTML Decode', href: '#' },
       { title: 'XML URL Encoding', href: '#' },
       { title: 'XML URL Decoding', href: '#' },
       { title: 'UTF8 Converter', href: '#' },
       { title: 'UTF8 Decode', href: '#' },
       { title: 'Hex to UTF8', href: '#' },
       { title: 'JSON Decode Online', href: '#' },
       { title: 'JSON Encode Online', href: '#' },
     ],
   },
   {
     title: 'SQL Converters',
     live: false,
     links: [
       { title: 'SQL to CSV Converter', href: '#' },
       { title: 'SQL to JSON Converter', href: '#' },
       { title: 'SQL to XML Converter', href: '#' },
       { title: 'SQL to YAML Converter', href: '#' },
       { title: 'SQL to HTML Converter', href: '#' },
     ],
   },
   {
     title: 'Unit Converter',
     live: false,
     links: [
       { title: 'Length Converter', href: '#' },
       { title: 'Weight Converter', href: '#' },
       { title: 'Volume Converter', href: '#' },
       { title: 'Area Converter', href: '#' },
       { title: 'Time Converter', href: '#' },
       { title: 'Unix Timestamp Converter', href: '#' },
       { title: 'More Unit Tools', href: '#' },
     ],
   },
   {
     title: 'Color Converters',
     live: false,
     links: [
       { title: 'HEX to Pantone Converter', href: '#' },
       { title: 'RGB to Pantone Converter', href: '#' },
       { title: 'HSV to Pantone Converter', href: '#' },
       { title: 'CMYK to Pantone Converter', href: '#' },
       { title: 'CMYK to HEX Converter', href: '#' },
       { title: 'CMYK to RGB Converter', href: '#' },
       { title: 'CMYK to HSV Converter', href: '#' },
       { title: 'HSV to HEX Converter', href: '#' },
       { title: 'HSV to RGB Converter', href: '#' },
       { title: 'HSV to CMYK Converter', href: '#' },
       { title: 'HEX to HSV Converter', href: '#' },
       { title: 'RGB to HEX Converter', href: '#' },
       { title: 'RGB to HSV Converter', href: '#' },
       { title: 'RGB to CMYK Converter', href: '#' },
       { title: 'HEX to RGB Converter', href: '#' },
       { title: 'HEX to CMYK Converter', href: '#' },
       { title: 'Pantone to HEX Converter', href: '#' },
       { title: 'Pantone to RGB Converter', href: '#' },
       { title: 'Pantone to CMYK Converter', href: '#' },
       { title: 'Pantone to HSV Converter', href: '#' },
     ],
   },
 ]


module.exports = {
  navigation,
}
